name: face-recognition2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge/label/cf201901
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
name: deepenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - opencv
  - cmake
  - dlib
  - libpng
  - jpeg
  - zlib
  - mkl
  - tbb
  - sqlite
  - ca-certificates
  - openssl
  - pip:
      - torch==2.16
      - torchvision==0.16.1
      - torchaudio==2.1.6
      - tensorflow==2.17.0
      - tensorboard==2.17.0
      - keras
      - face-recognition
      - face-recognition-models
      - absl-py
      - h5py>=3.10
      - protobuf>=4.21
      - scikit-learn
      - pillow
      - requests
      - jinja2
      - werkzeug
      - typing-extensions
      - importlib-metadata
      - tqdm
      - pyyaml
      - prettytable
      - simplejson
      - ttkbootstrap
      - pyecharts
